[USER] Added UserService
jv-jun23-team5/car-sharing-app pull request #12
Opened 2023-10-03 13:05 UTC by OleksandrSaven

2023-10-03 16:42 UTC, DmytroV95 requested changes
GJ! Left comments to improve your solution.

2023-10-03 16:42 UTC, DmytroV95 commented on src/main/java/com/project/carsharingapp/model/Role.java
> +        CUSTOMER
```suggestion
        ROLE_MANAGER,
        ROLE_CUSTOMER

```

2023-10-03 16:42 UTC, DmytroV95 commented on src/main/java/com/project/carsharingapp/services/impl/UserServiceImpl.java
> +                () -> new RuntimeException("Can't find user by id " + id));
You are using this code in different methods. Make it as separate method and reuse it. Also use our custom EntityNotFoundException

2023-10-03 16:42 UTC, DmytroV95 commented on src/main/java/com/project/carsharingapp/services/impl/UserServiceImpl.java
> +                () -> new RuntimeException("Can't find user by id " + id));
Same

2023-10-03 16:42 UTC, DmytroV95 commented on src/main/java/com/project/carsharingapp/services/impl/UserServiceImpl.java
> +                () -> new RuntimeException("Can't find user by id " + id));
Same

2023-10-03 16:47 UTC, OleksandrSaven commented on src/main/java/com/project/carsharingapp/services/impl/UserServiceImpl.java
> +                () -> new RuntimeException("Can't find user by id " + id));
I know, when I made this  service, there was no GlobalExeptionHandler

2023-10-04 05:40 UTC, DmytroV95 approved these changes
LGTM!

2023-10-04 08:15 UTC, merged