[PAYMENT] implemented beta controller and service, added swagger to the controller
jv-jun23-team5/car-sharing-app pull request #16
Opened 2023-10-03 16:11 UTC by ivan0dyatlyukkk

2023-10-03 17:24 UTC, OlegStashkiv approved these changes

2023-10-03 17:24 UTC, OlegStashkiv commented on src/main/java/com/project/carsharingapp/controller/PaymentController.java
> +        System.out.println(url);
I think it's better to remove it

2023-10-03 18:51 UTC, DmytroV95 requested changes
Super! GJ! Left some minor comments.

2023-10-03 18:51 UTC, DmytroV95 commented on src/main/java/com/project/carsharingapp/controller/PaymentController.java
> +@Tag(name = "Payment controller", description = "Endpoint for managing payments")
```suggestion
@Tag(name = "Payment management", description = "Endpoint for managing payments")
```
To make a uniform style for controllers.

2023-10-03 18:51 UTC, DmytroV95 commented on src/main/java/com/project/carsharingapp/dto/payment/CreatePaymentSessionRequestDto.java
> +@Data
```suggestion
@Getter
@Setter
```

2023-10-03 18:51 UTC, DmytroV95 commented on src/main/java/com/project/carsharingapp/dto/payment/PaymentResponseDto.java
> +public class PaymentResponseDto {
What is the purpose of using empty class?

2023-10-03 18:51 UTC, DmytroV95 commented on src/main/java/com/project/carsharingapp/service/impl/StripeService.java
> +
Redundant line

2023-10-03 18:51 UTC, DmytroV95 commented on src/main/java/com/project/carsharingapp/service/impl/StripeService.java
> +    private final PaymentAmountHandlerStrategy handler;
Add whitespace between static and not static fields.

2023-10-04 09:57 UTC, OleksandrSaven approved these changes
LGTM!

2023-10-04 10:01 UTC, merged