"[TESTING] Added test cases for CarServiceImpl"
jv-jun23-team5/car-sharing-app pull request #31
Opened 2023-10-04 17:30 UTC by AntonZhdanov

2023-10-04 18:24 UTC, ivan0dyatlyukkk requested changes
GJ! But please, check my suggestions :)

2023-10-04 18:24 UTC, ivan0dyatlyukkk commented on docker-compose.yml
> +    env_file: .env.sample
Please, replace this custom option to the previous one

2023-10-04 18:24 UTC, ivan0dyatlyukkk commented on docker-compose.yml
> +    env_file: .env.sample
The same

2023-10-05 11:00 UTC, OlegStashkiv requested changes
The tests themselves are ok. Just correct my and Ivan's remark

2023-10-05 11:00 UTC, OlegStashkiv commented on .gitignore
> +.env.sample
This should not be here. We are pushing this file

2023-10-05 12:00 UTC, OlegStashkiv approved these changes

2023-10-05 12:04 UTC, ivan0dyatlyukkk approved these changes

2023-10-05 12:04 UTC, merged